### ISSUE TITLE
9 April

### ISSUE THREAD

**Issue by 6arin** [6arin/Space_Program#2]
- [ ]  8:00 - Wake up
- [ ]  8:00 - 8:20 Более серьезная тренировка, чем вчера
- [ ]  8:20 - 8:35 Душ, более холодный чем вчера
- [ ]  8:35 - 9:00 Завтрак, жевать быстрее чем вчера

- [ ]  9:00 - 9:20  issue #6 MDPL
- [ ]  9:20 - 9:30  issue #3 MDPL
- [ ]  9:30 - 10:00 issue #7 MDPL
- [ ] 10:00 - 10:30 доделать, если что-то не получилось + issue 4

- [ ] 10:30 - 11:00 Поговорить на английском
- [ ] 11:00 - 11:30 issue 7  CG
- [ ] 11:30 - 12:00 issue 11 CG
- [ ] 12:00 - 12:30 issue 8  CG
- [ ] 12:30 - 13:00 issue 9  CG
 
- [ ] 13:00 - 14:00 Обед + чтение + затестить дискорд
- [ ] 14:00 - 14:30 Накидать issue по lab#3 MDPL

- [ ] Если появляется ясность делать MDPL, иначе ВычАлг
 ------------------------------------------
- [ ] PLAN A
- [ ] 14:30 - 16:00 Работа по issue MDPL
 ------------------------------------------
- [ ] PLAN B
- [ ] 14:30 - 15:00 Накидать issue по ВычАлг#1
- [ ] 15:00 - 16:00 Работа по issue ВычАлг#1
 ------------------------------------------

- [ ] 16:00 - 16:30 English vocabulary
- [ ] 16:30 - 17:00 Голос

- [ ] 17:00 - 17:20 Декомпозиция ООП
- [ ] 17:20 - 17:40 Декомпозиция АрхЭВМ 
- [ ] 17:40 - 18:00 Ужин

- [ ] 18:00 - 19:00 Теория Игр (все видео материалы к недели 1 + конспекты. выделить тетрадь)
- [ ] 19:00 - 20:00 тренировка
- [ ] 20:00 - 21:00 Запасной час или Free Time

- [ ] 21:00 - 21:15 MDPL RK#1: вопрос 1
- [ ] 21:15 - 21:30 MDPL RK#1: вопрос 2
- [ ] 21:30 - 21:45 MDPL RK#1: вопрос 3
- [ ] 21:45 - 22:00 MDPL RK#1: вопрос 4

- [ ] - 22:00 - 23:00 Подведение итогов и планирование
- [ ] - 23:00 - 00:00 Чтение
